name: Demo
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
jobs:
  demo:
    name: just demos running a workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: hello world
      run: echo "hello world"
